import { COLORS } from './colors';
import { FONT_STYLES } from './fontStyles';
import {
  TAB_SCREENS,
  LOCATION_SCREENS,
  CHAT_SCREENS,
  INBOX_SCREENS,
  ACCOUNT_SCREENS,
  NETWORK_SCREENS,
  PRODUCT_DESCRIPTION_SCREENS,
  SELL_SCREENS,
  ADS_SCREENS,
  ADS_TAB_SCREENS,
  HOME_SCREENS,
} from './screen';
import { SIZE } from './size';
import { TAB_LABELS } from './tabLabels';

export {
  TAB_SCREENS,
  TAB_LABELS,
  COLORS,
  FONT_STYLES,
  LOCATION_SCREENS,
  SIZE,
  CHAT_SCREENS,
  INBOX_SCREENS,
  ACCOUNT_SCREENS,
  NETWORK_SCREENS,
  PRODUCT_DESCRIPTION_SCREENS,
  SELL_SCREENS,
  ADS_SCREENS,
  HOME_SCREENS,
  ADS_TAB_SCREENS,
};
